
# API proxying
[[redirects]]
    from = "/api/*"
    to = "https://inislam.herokuapp.com/:splat"
    status = 200
    force = true
    
    
# React Router support
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200